name:         androidicongenerator
author:       "Mike Mitterer <office@mikemitterer.at>"
#homepage: https://github.com/dart-lang/html5lib
description:  Generates Icons for Android-Devices
version:      0.1.0

dependencies:
  # web_ui: "0.2.11"
  web_ui: any
  unittest: any
  browser: any 
  # color_picker: any
  # color_picker: ">=1.0.0 <2.0.0"
