name: androidicongenerator
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
description: Generates Icons for Android-Devices
dependencies:
  browser: any
  crypto: any
  unittest: any
  web_ui: any

#web_ui: 0.3.1+3
#homepage: https://github.com/dart-lang/html5lib
# web_ui: "0.2.11"
# color_picker: any
# color_picker: ">=1.0.0 <2.0.0"